### ISSUE TITLE
.JWTheartbreaker does not exist

### ISSUE THREAD

**Issue by EthicalHCOP** [wallarm/jwt-heartbreaker#1]
Hello.
i got this message when I try to load the extension.

`09:12:10.608 | Config file directory '.JWTheartbreaker' does not exist - creating it`
`09:12:10.609 | Config file 'C:\Users\Myuser\.JWTheartbreaker\config.json' does not exist - creating it`

I downloaded the jar file from the releases and when I put it in burp, i got this error ! 
i don't see the config.json in the repo  !

**Comment by d0znpp** [comment]
It's normal behavior for the first time run.
